# # template
# name: cebpubservice_tenderdocumenttemplate
# base_list_url: http://www.cebpubservice.com/tenderdocument/mhDocumentLibNoSessionAction/queryTenderdocumentTemplateHtml.do

# hot
name: hebeieb_bid_call
base_url: http://www.hebeieb.com
base_list_url: http://www.hebeieb.com/tender/xxgk/zbgg.do
output_dir: outputs
download_api: "http://www.hebeieb.com/infogk/newDetail.do"
proxy_host: "localhost"
proxy_port: "26888"
mongo_host: "localhost"
mongo_port: 27018
mongo_db: hebeieb
mongo_collection: ${name}
timeout: 10.0
start_page_num: 1
tot_page_num: 500
sleep: 1.5
max_request_attempt: 5
